//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopWidgets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopWidgets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DesktopWidgets.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/danielchalmers/DesktopWidgets/commits.
        /// </summary>
        public static string GitHubApiCommits {
            get {
                return ResourceManager.GetString("GitHubApiCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/danielchalmers/DesktopWidgets/commits.
        /// </summary>
        public static string GitHubCommits {
            get {
                return ResourceManager.GetString("GitHubCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/danielchalmers/DesktopWidgets/issues.
        /// </summary>
        public static string GitHubIssues {
            get {
                return ResourceManager.GetString("GitHubIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/danielchalmers/DesktopWidgets.
        /// </summary>
        public static string GitHubMainPage {
            get {
                return ResourceManager.GetString("GitHubMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.openweathermap.org/.
        /// </summary>
        public static string OpenWeatherMapDomain {
            get {
                return ResourceManager.GetString("OpenWeatherMapDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .widget.
        /// </summary>
        public static string PackageExtension {
            get {
                return ResourceManager.GetString("PackageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget package (*.widget)|*.widget|All files (*.*)|*.*.
        /// </summary>
        public static string PackageExtensionFilter {
            get {
                return ResourceManager.GetString("PackageExtensionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar.
        /// </summary>
        public static string TaskBarPath {
            get {
                return ResourceManager.GetString("TaskBarPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to desktop.ini.
        /// </summary>
        public static string WindowsFolderDataFile {
            get {
                return ResourceManager.GetString("WindowsFolderDataFile", resourceCulture);
            }
        }
    }
}
